export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";

// ADMIN
export const GET_ADMIN_PRODUCTS = "GET_ADMIN_PRODUCTS";
export const GET_USERS = "GET_USERS";
export const GET_DISCOUNTS = "GET_DISCOUNTS";
export const GET_ADMIN_ORDERS = "GET_ADMIN_ORDERS";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_DISCOUNT = "ADD_DISCOUNT";

export const EDIT_USER = "EDIT_USER";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_ADMIN_ORDER = "EDIT_ADMIN_ORDER";

export const DELETE_USER = "DELETE_USER";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_DISCOUNT = "DELETE_DISCOUNT";

// CART

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const REMOVE_QUANTITY = "REMOVE_QUANTITY";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";

// ORDER

export const ADD_DISCOUNT_ORDER = "ADD_DISCOUNT_ORDER";
export const CHECK_AUTH_AND_CHECKOUT = "CHECK_AUTH_AND_CHECKOUT";
export const ADD_SHIPPING_DATA = "ADD_SHIPPING_DATA";
export const CLEAR_ORDER = "CLEAR_ORDER";
